### ISSUE TITLE
Turning on auto-merge for DependaBot updates

### ISSUE THREAD

**Issue by nschonni** [nodejs/remark-preset-lint-node#121]
Since we have good coverage of the tests running against the core docs, I think letting DependaBot land PRs when the tests pass should be safe.
Could convert over to the new Yaml config later, but I'm not seeing that setting in their docs right now.

**Comment by nschonni** [comment]
@Trott what do you thing, since you've been landing a bunch of those PRs that came through recently?

**Comment by Trott** [comment]
I think it's a fine idea. I don't know if it can be turned on for just this repository, or where the settings are, but if someone else wants to make it happen, or if someone wants to guide me to the right place to go to turn this on, great.

**Comment by nschonni** [comment]
OK, I've turned it on for this repository over on https://app.dependabot.com/accounts/nodejs/projects/160714

**Comment by nschonni** [comment]
FYI, looks like there are 2 blockers now for switching to the config setup
```
You're using unsupported features

Your account is using automerging. There is no automerging support in GitHub-native Dependabot, so these settings will not be added to the new config file. Several 3rd-party GitHub Actions and bots can replicate the automerge feature.

You have disabled "Create a merge commit if a PR is merged by Dependabot". This setting no longer supported, so these settings will not be added to the new config file.
```
