### ISSUE TITLE
Setup CI for testing changes

### ISSUE THREAD

**Issue by nschonni** [nodejs/remark-preset-lint-node#19]
Was thinking that Travis could probably be setup to clone down the nodejs/node repo, and any other nodejs repos that are using this to see if changes to the config cause new issues.

**Comment by Trott** [comment]
Probably OK to just do the main node repo. New rules will only go out when we publish new versions. So other projects can fix up their markdown when they upgrade (which is what we do when we upgrade ESLint and an existing rule becomes more strict, for example).

**Comment by nschonni** [comment]
OK, I had tried to add the node master branch as an NPM dev dependency, but that didn't work.
I'll give a basic Travis a try, if you don't get to it first.
