### ISSUE TITLE
Remark's move to ESM

### ISSUE THREAD

**Issue by nschonni** [nodejs/remark-preset-lint-node#207]
It looks like Remark moved there new stuff to ESM, so the current new PRs are failing:
- https://github.com/nodejs/remark-preset-lint-node/pull/202
- https://github.com/nodejs/remark-preset-lint-node/pull/206

Doesn't seem like anything is going to be done for the old versions, so it's upgrade here to ESM, or lose support.

**Comment by Trott** [comment]
I've been waiting for `remark-lint` to be ESM-compatible before doing anything. It's README still shows "require" and not "import".... https://github.com/remarkjs/remark-lint

**Comment by aduh95** [comment]
FWIW I know `remark-lint` can be used from ESM, although it's less elegant:

```js
const importDefault = (specifier) =>
  import(specifier).then((module) => module.default);

export default {
  plugins: [
    await importDefault("remark-lint"),
    // etc.
  ]
};
```

or using static imports, but that requires to find a JS name for each package:

```js
import remarkLint from "remark-lint";

export default {
  plugins: [
    remarkLint,
    // etc.
  ]
};
```

**Comment by nschonni** [comment]
Ah I see, I guess it's the remark(-cli) part that has migrated so far. We can keep this open, since it looks like they're in the process of ESM-ing the other parts right now

**Comment by nschonni** [comment]
looks like the CLI bump is ok on the dependant repos https://github.com/nodejs/TSC/pull/1069

**Comment by nschonni** [comment]
Actually, it doesn't like the plug-in bump https://github.com/nodejs/TSC/pull/1068

**Comment by Trott** [comment]
> Actually, it doesn't like the plug-in bump [nodejs/TSC#1068](https://github.com/nodejs/TSC/pull/1068)

After I landed the `remark-cli` bump, the plug-in bump succeeded.

**Comment by nschonni** [comment]
Looks like `remark-lint` pushed the ESM version now too. I'll give it a try with the conversion

**Comment by Trott** [comment]
> Looks like `remark-lint` pushed the ESM version now too. I'll give it a try with the conversion

@nschonni Oooh, hope you didn't get too far! I'm doing the conversion right now and am almost done! But if you beat me to it, that's A-OK!

**Comment by Trott** [comment]
https://github.com/nodejs/remark-preset-lint-node/pull/217
