### ISSUE TITLE
3.0.0 checks are broken?

### ISSUE THREAD

**Issue by aduh95** [nodejs/remark-preset-lint-node#219]
Does the fact that this succeeded means the unordered links check isn't working in 3.0.0? @nschonni

_Originally posted by @Trott in https://github.com/nodejs/TSC/issues/1072#issuecomment-899168735_

I've also noticed https://github.com/nodejs/node/pull/39754#issuecomment-899144843, where a user is using a malformed version string, which `nodejs-yaml-comments` should be picking up, but the GH Action is green still.

**Comment by nschonni** [comment]
I guess it might be time for a few unit tests in addition to the integration test on the full repo we have now

**Comment by Trott** [comment]
I've got the fix coming momentarily.

**Comment by Trott** [comment]
Fix is in https://github.com/nodejs/remark-preset-lint-node/pull/249
