### ISSUE TITLE
Expand test to cover all documents the nodejs/node lints

### ISSUE THREAD

**Issue by nschonni** [nodejs/remark-preset-lint-node#31]
Currently the CI test only covers the docs, but there are a few additional directories that the main repo checks https://github.com/nodejs/node/blob/5f80df882057522c38c30b99f4bf25d82c68f662/Makefile#L1196-L1200
The current remark-lint way of ignoring globs might not work, so a test script or some `&&` calls might be required

**Comment by XhmikosR** [comment]
Just please remember Windows too. I personally use [shx](https://github.com/shelljs/shx) in npm scripts for cross-platform commands.

If you make a PR feel free to ping me.
