### ISSUE TITLE
Automate NPM release with semantic-release

### ISSUE THREAD

**Issue by nschonni** [nodejs/remark-preset-lint-node#329]
Came across this in https://github.com/htmlhint/HTMLHint/blob/1e85c6eb86bfabd0d4ca7a19ee2842706b449b48/.github/workflows/production.yml#L105-L121 https://github.com/htmlhint/HTMLHint/blob/master/.releaserc.json

Uses convetional commit message formatting to auto-cut release if anything beyond a `chore` is landed.

I know there is still a manual process to land it in `nodejs/node`, but was thinking it might be helpful for the other repos to be able to get Dependabot PRs for new releases from this repo.

Downside is that maybe it would still lead to more release churn, and would also probably need an issue on `nodejs/admin` for the token setup

**Comment by Trott** [comment]
I use semantic-release on all my personal repos and would be comfortable with doing the same here. If you want to open the issue in the admin repo, I'll certainly +1 it.

**Comment by nschonni** [comment]
OK, what actually needs to get requested? I'm guessing that you're currently releasing under your own token, but do we need to request the bot token instead?

**Comment by Trott** [comment]
I think there's an org token or something like that? I think @mmarchini knows about this stuff.

**Comment by Trott** [comment]
This is now done.
